### PR TITLE
fix: Skip static partial method instrumentation

### LINKED ISSUE #320: 'functools.partial' objects used as static methods cause crash
This exception is raised in many [`sympy` v1.0](https://github.com/sympy/sympy/tree/sympy-1.0) test cases.
```
Traceback (most recent call last):
  File "/tmp/tmpz56qw_4w/sympy__sympy__1.0/sympy/utilities/runtests.py", line 1129, in wrapper
    test_func()
  File "/tmp/tmpz56qw_4w/sympy__sympy__1.0/sympy/assumptions/tests/test_matrices.py", line 78, in test_unitary
    _test_orthogonal_unitary(Q.unitary)
  File "/tmp/tmpz56qw_4w/sympy__sympy__1.0/sympy/assumptions/tests/test_matrices.py", line 63, in _test_orthogonal_unitary
    assert ask(predicate(X), predicate(X))
  File "/home/db/dev/applandinc/appmap-python/_appmap/wrapt/wrappers.py", line 622, in __call__
    return self._self_wrapper(self.__wrapped__, self._self_instance,
  File "/home/db/dev/applandinc/appmap-python/_appmap/instrument.py", line 129, in instrumented_fn
    return call_instrumented(f, instance, args, kwargs)
  File "/home/db/dev/applandinc/appmap-python/_appmap/instrument.py", line 92, in call_instrumented
    ret = f.fn(*args, **kwargs)
  File "/tmp/tmpz56qw_4w/sympy__sympy__1.0/sympy/assumptions/ask.py", line 1272, in ask
    res = key(expr)._eval_ask(assumptions)
  File "/tmp/tmpz56qw_4w/sympy__sympy__1.0/sympy/assumptions/assume.py", line 112, in _eval_ask
    return self.func.eval(self.arg, assumptions)
  File "/tmp/tmpz56qw_4w/sympy__sympy__1.0/sympy/assumptions/assume.py", line 176, in eval
    cls = get_class(handler)
  File "/tmp/tmpz56qw_4w/sympy__sympy__1.0/sympy/utilities/source.py", line 29, in get_class
    __import__(mod_name, {}, {}, ['*']), func_name)
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/home/db/dev/applandinc/appmap-python/_appmap/wrapt/wrappers.py", line 613, in __call__
    return self._self_wrapper(self.__wrapped__, instance,
  File "/home/db/dev/applandinc/appmap-python/_appmap/importer.py", line 240, in wrapped_exec_module
    Importer.do_import(*args, **kwargs)
  File "/home/db/dev/applandinc/appmap-python/_appmap/importer.py", line 209, in do_import
    instrument_functions(fc)
  File "/home/db/dev/applandinc/appmap-python/_appmap/importer.py", line 180, in instrument_functions
    functions = get_members(filterable.obj)
  File "/home/db/dev/applandinc/appmap-python/_appmap/importer.py", line 134, in get_members
    if value.__module__ != modname:
AttributeError: 'functools.partial' object has no attribute '__module__'
```

conda env
```
name: sympy__sympy__1.0
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2024.3.11=h06a4308_0
  - flake8=7.0.0=py39h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - mccabe=0.7.0=pyhd3eb1b0_0
  - mpmath=1.3.0=py39h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.13=h7f8727e_2
  - pip=24.0=py39h06a4308_0
  - pycodestyle=2.11.1=py39h06a4308_0
  - pyflakes=3.2.0=py39h06a4308_0
  - python=3.9.19=h955ad1f_1
  - readline=8.2=h5eee18b_0
  - setuptools=69.5.1=py39h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - tzdata=2024a=h04d1e81_0
  - wheel=0.43.0=py39h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - appmap==2.0.0
      - flake8-comprehensions==3.14.0
      - importlib-resources==5.13.0
      - inflection==0.5.1
      - packaging==24.0
      - pyyaml==6.0.1
      - zipp==3.18.2
prefix: /home/db/miniconda3/envs/sympy__sympy__1.0
```

### PR DESCRIPTION
**Pull request by dustinbyrne**
Previously, static partial methods would raise an exception: AttributeError: 'functools.partial' object has no attribute '__module__'

Fixes #320

### CODE REVIEW

**Comment by kgilpin** [comment]
What does Navie say about this issue?

**Comment by apotterri** [comment]
I'm currently working on a less-intrusive fix for this issue. I think I'd like to see how that pans out before we make these changes to `importer.py`.

I'll add the your test case to my changes and make sure it works with them. Thanks!

**Comment by dustinbyrne** [comment]
> What does Navie say about this issue?

I used Navie for the basis of this fix. It wasn't able to solve the issue outright, as it turned out that actually replicating the issue was the difficult bit, but watching it try to solve it was enough for me to implement the fix. I didn't intend to pick this issue up, but I used it as a test bed for something else and ultimately got far enough that I figured I should finish it.

https://gist.github.com/dustinbyrne/26a1a26fa79ac6f4292ca3ab4afb2abd

**Comment by kgilpin** [comment]
I guess we need Navie to summarize these chats :-)

**Pull request closed without merging**
