### PR TITLE
fix: reenable instrumentation of properties

### LINKED ISSUE #320: 'functools.partial' objects used as static methods cause crash
This exception is raised in many [`sympy` v1.0](https://github.com/sympy/sympy/tree/sympy-1.0) test cases.
```
Traceback (most recent call last):
  File "/tmp/tmpz56qw_4w/sympy__sympy__1.0/sympy/utilities/runtests.py", line 1129, in wrapper
    test_func()
  File "/tmp/tmpz56qw_4w/sympy__sympy__1.0/sympy/assumptions/tests/test_matrices.py", line 78, in test_unitary
    _test_orthogonal_unitary(Q.unitary)
  File "/tmp/tmpz56qw_4w/sympy__sympy__1.0/sympy/assumptions/tests/test_matrices.py", line 63, in _test_orthogonal_unitary
    assert ask(predicate(X), predicate(X))
  File "/home/db/dev/applandinc/appmap-python/_appmap/wrapt/wrappers.py", line 622, in __call__
    return self._self_wrapper(self.__wrapped__, self._self_instance,
  File "/home/db/dev/applandinc/appmap-python/_appmap/instrument.py", line 129, in instrumented_fn
    return call_instrumented(f, instance, args, kwargs)
  File "/home/db/dev/applandinc/appmap-python/_appmap/instrument.py", line 92, in call_instrumented
    ret = f.fn(*args, **kwargs)
  File "/tmp/tmpz56qw_4w/sympy__sympy__1.0/sympy/assumptions/ask.py", line 1272, in ask
    res = key(expr)._eval_ask(assumptions)
  File "/tmp/tmpz56qw_4w/sympy__sympy__1.0/sympy/assumptions/assume.py", line 112, in _eval_ask
    return self.func.eval(self.arg, assumptions)
  File "/tmp/tmpz56qw_4w/sympy__sympy__1.0/sympy/assumptions/assume.py", line 176, in eval
    cls = get_class(handler)
  File "/tmp/tmpz56qw_4w/sympy__sympy__1.0/sympy/utilities/source.py", line 29, in get_class
    __import__(mod_name, {}, {}, ['*']), func_name)
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/home/db/dev/applandinc/appmap-python/_appmap/wrapt/wrappers.py", line 613, in __call__
    return self._self_wrapper(self.__wrapped__, instance,
  File "/home/db/dev/applandinc/appmap-python/_appmap/importer.py", line 240, in wrapped_exec_module
    Importer.do_import(*args, **kwargs)
  File "/home/db/dev/applandinc/appmap-python/_appmap/importer.py", line 209, in do_import
    instrument_functions(fc)
  File "/home/db/dev/applandinc/appmap-python/_appmap/importer.py", line 180, in instrument_functions
    functions = get_members(filterable.obj)
  File "/home/db/dev/applandinc/appmap-python/_appmap/importer.py", line 134, in get_members
    if value.__module__ != modname:
AttributeError: 'functools.partial' object has no attribute '__module__'
```

conda env
```
name: sympy__sympy__1.0
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2024.3.11=h06a4308_0
  - flake8=7.0.0=py39h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - mccabe=0.7.0=pyhd3eb1b0_0
  - mpmath=1.3.0=py39h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.13=h7f8727e_2
  - pip=24.0=py39h06a4308_0
  - pycodestyle=2.11.1=py39h06a4308_0
  - pyflakes=3.2.0=py39h06a4308_0
  - python=3.9.19=h955ad1f_1
  - readline=8.2=h5eee18b_0
  - setuptools=69.5.1=py39h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - tzdata=2024a=h04d1e81_0
  - wheel=0.43.0=py39h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - appmap==2.0.0
      - flake8-comprehensions==3.14.0
      - importlib-resources==5.13.0
      - inflection==0.5.1
      - packaging==24.0
      - pyyaml==6.0.1
      - zipp==3.18.2
prefix: /home/db/miniconda3/envs/sympy__sympy__1.0
```

### LINKED ISSUE #357: Properties that use `operator.attrgetter` as their getter cause an error
This was originally discovered when trying to run tests in django:

```
ERROR: test_works_normally (generic_relations.tests.ProxyRelatedModelTest)
When for_concrete_model is False, we should still be able to get
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/kgilpin/source/land-of-apps/django/venv/lib/python3.10/site-packages/_appmap/wrapt/wrappers.py", line 719, in __call__
    return self._self_wrapper(self.__wrapped__, self._self_instance,
  File "/Users/kgilpin/source/land-of-apps/django/venv/lib/python3.10/site-packages/_appmap/unittest.py", line 39, in callTestMethod
    wrapped(test_method, **kwargs)
  File "/usr/local/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
...
File "/Users/kgilpin/source/land-of-apps/django/venv/lib/python3.10/site-packages/_appmap/instrument.py", line 88, in call_instrumented
    call_event = f.make_call_event(parameters=params)
  File "/Users/kgilpin/source/land-of-apps/django/venv/lib/python3.10/site-packages/_appmap/event.py", line 318, in __init__
    self._fqfn = FqFnName(fn)
  File "/Users/kgilpin/source/land-of-apps/django/venv/lib/python3.10/site-packages/_appmap/utils.py", line 85, in __init__
    qualname = fn.__qualname__
AttributeError: 'operator.attrgetter' object has no attribute '__qualname__'
```

### PR DESCRIPTION
**Pull request by apotterri**
Have APPMAP_INSTRUMENT_PROPERTIES default to true once again.

Special-case properties that have operator.attrgetter as their getter. Django uses this pattern extensively, and this special-case fixes some failures when trying to generate AppMap data for Django tests.

Also, make sure that examining a `partial` that's being used as a static method doesn't crash.
Fixes #357.
Fixes #320 .

### CODE REVIEW

**Review by dividedmind — APPROVED** [review]
Looks ok, but my concern is that it's special-cased on attrgetter and therefore can be incomplete. What if the getter is another free function? Say, an `itemgetter` or something user-defined?

**Comment by apotterri** [comment]
If the getter is another free function, `type(fn)` will not be `operator.attrgetter`, and so it will take the first branch (and set `modname` and `qualname` from the function). Seems like this should be fine?

If it's a different builtin, it'll hit the third branch, and set `modname` and `qualname` to `"unknown"`.  Not ideal, but at least it won't crash....

**Comment by dividedmind** [comment]
> If the getter is another free function, `type(fn)` will not be `operator.attrgetter`, and so it will take the first branch (and set `modname` and `qualname` from the function). Seems like this should be fine?
> 
> If it's a different builtin, it'll hit the third branch, and set `modname` and `qualname` to `"unknown"`. Not ideal, but at least it won't crash....

I just tried with itemgetter:
```
_appmap/instrument.py:88: in call_instrumented
    call_event = f.make_call_event(parameters=params)
_appmap/event.py:324: in __init__
    qualname = fn.__qualname__
E   AttributeError: 'operator.itemgetter' object has no attribute '__qualname__'
```

and with a user function:
```
E   AssertionError: assert {'auxtype': '... 'id': 1, ...} == {'event': 'ca...d_only (get)'}
E     Omitting 1 identical items, use -vv to show
E     Differing items:
E     {'defined_class': 'properties_class'} != {'defined_class': 'properties_class.PropertiesClass'}
E     {'method_id': 'stringify_prop_class (get)'} != {'method_id': 'operator_read_only (get)'}
```
(This used `operator_read_only = property(stringify_prop_class)`, where `stringify_prop_class` is a free funciton in the module; seems like this could be mostly fine actually, except it shouldn't say `(get)`.)

**Comment by apotterri** [comment]
The change I'm working on fixes the first case, using a default if `not hasattr(fn, '__qualname__')`.

Re the second case: can you provide the changes to PropertiesClass, and the modified test case, please? I'll add them to the PR.

**Review by dividedmind — APPROVED** [review]

**Pull request merged**
